version: 2.0
jobs:
  build:
    branches:
      only:
        - master
        - /circleci-.*/
    docker: 
      - image: gitpitch/ci:latest
        auth:
            username: davidmrussell
            password: $TEST_DOCKERHUB_PASSWORD
    working_directory: /repo
    steps:
      - checkout
      - run: /gitpitchci/start.sh
      - store_artifacts:
          path: /gitpitch/artifacts
      - persist_to_workspace:
          root: /gitpitch
          paths:
              artifacts
